CREATE DATABASE COMPANY_db;

USE COMPANY_db;

CREATE TABLE DEPARTMENT (
DEPT_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
DEPT_NAME VARCHAR(100) NOT NULL,
LOCATION VARCHAR(100)
);

CREATE TABLE EMPLOYEE (
EMP_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
EMP_NAME VARCHAR(100) NOT NULL,
GENDER INT DEFAULT 1,
BIRTH_DATE DATE,
SALARY DECIMAL(10,2),
DEPT_ID INT,
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID) ON UPDATE CASCADE
);

CREATE TABLE PROJECT (
PROJECT_ID INT PRIMARY KEY auto_increment NOT NULL,
PROJECT_NAME VARCHAR(150) NOT NULL,
EMP_ID INT,
foreign key (EMP_ID) references EMPLOYEE(EMP_ID),
START_DATE DATE DEFAULT(CURRENT_DATE),
END_DATE DATE
);

ALTER TABLE EMPLOYEE
ADD EMAIL VARCHAR(100) UNIQUE;

ALTER TABLE PROJECT
MODIFY PROJECT_NAME VARCHAR(200);

ALTER TABLE PROJECT
ADD CONSTRAINT CHECK_DATE
CHECK(END_DATE>=START_DATE);

INSERT INTO DEPARTMENT(DEPT_ID,DEPT_NAME,LOCATION)
values 
(1,'IT','HA NOI'),
(2,'HR','HCM'),
(3,'MARKETING','DA NANG');

INSERT INTO EMPLOYEE
(EMP_ID, EMP_NAME, GENDER, BIRTH_DATE, SALARY, DEPT_ID, EMAIL)
VALUES
(1, 'Nguyen Van A', 1, '1990-01-15', 1500, 1, 'a@gmail.com'),
(2, 'Tran Thi B', 0, '1995-05-20', 1200, 1, 'b@gmail.com'),
(3, 'Le Minh C', 1, '1988-10-10', 2000, 2, 'c@gmail.com'),
(4, 'Pham Thi D', 0, '1992-12-05', 1800, 3, 'd@gmail.com');

INSERT INTO PROJECT (PROJECT_ID, PROJECT_NAME, EMP_ID, START_DATE, END_DATE)
VALUES
(101, 'Website Redesign', 1, '2024-01-01', '2024-06-01'),
(102, 'Recruitment System', 3, '2024-02-01', '2024-08-01'),
(103, 'Marketing Campaign', 4, '2024-03-01', NULL);

UPDATE EMPOLYEE
SET SALARY = SALARY + 200
WHERE DEPT_ID = 1;

UPDATE PROJECT
SET END_DATE = '2024-12-31'
WHERE END_DATE IS NULL;

DELETE FROM PROJECT
WHERE START_DATE < '2024-02-01';

SELECT EMP_NAME,EMAIL,
CASE
	WHEN GENDER = 1 THEN 'Nam'
	ELSE 'Nu'
    END AS GENDER_NAME
FROM EMPLOYEE;

SELECT
UPPER(EMP_NAME) AS EMP_NAME_UPPER,
YEAR(NOW()) - YEAR(BIRTH_DATE) AS AGE
FROM EMPLOYEE;

SELECT E.EMP_NAME,E.SALARY,D.DEPT_NAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

SELECT * FROM EMPLOYEE
ORDER BY SALARY DESC
LIMIT 2;